name: aviatorbot
description: Aviator Predictor (local)
version: 1.0.0+1
publish_to: "none"  # Projet local, pas sur pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
